---

- name: Test distribution
  assert:
    that: >
      ansible_os_family == "RedHat" and
      ansible_distribution_major_version | int >= 7

- name: Install graphite-api RPM package
  yum:
    name: "{{ graphite_api_pkg }}"
  notify:
    - Restart graphite-api service
  tags:
    - graphite_api_pkg

- name: Install depending package
  yum:
    name: "{{ item }}"
  with_items: graphite_api_pkg_deps
  notify:
    - Restart graphite-api service
  tags:
    - graphite_api_pkg

- name: Configure graphite-api
  template:
    src: graphite-api.yaml.j2
    dest: /etc/graphite-api.yaml
  notify:
    - Restart graphite-api service
  tags:
    - graphite_api_config

- name: Configure graphite-api server
  template:
    src: graphite-api.default.j2
    dest: /etc/default/graphite-api
  notify:
    - Restart graphite-api service
  tags:
    - graphite_api_config

- name: Make graphite-api service running
  service:
    name: graphite-api
    state: started
    enabled: yes
